name: ca

on:
  workflow_dispatch:
  pull_request:
    types: [ assigned, opened, synchronize, reopened ]

jobs:
  build:
    runs-on: ubuntu-latest
    - name: create-draft
      run: |
        sudo make new-ca
        sudo make peek-ca
      