name: ca

on:
  pull_request:
  push:
    branch: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: generate
        run: |
          make new-ca
          