name: CA TESTS

on:
  pull_request:
  push:
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: ./CA/init.sh
