name: ins

on:
  workflow_dispatch:
  pull_request:
    types: [ assigned, opened, synchronize, reopened ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: ins
        run: |
          make tag-install
          outfile=".github/workflows/body.md"
          echo "## $(./tag)" > $outfile
          cat .github/workflows/template.md >> $outfile
          echo "succesfully built, signed & inserted the modules" >> $outfile
          sudo make full > tmp.bdg && head -n -10 tmp.bdg
          echo '\`\`\`' >> $outfile
          cat tmp.bdg >> $outfile
          echo '\`\`\`' >> $outfile

      - name: comment
        uses: harupy/comment-on-pr@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: "body.md"

      
