name: ins

on:
  workflow_dispatch:
  pull_request:
    types: [ assigned, opened, synchronize, reopened ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: ins
        run: |
          make tag-install
          outfile=".github/workflows/body.md"
          echo "## $(./tag)" > $outfile
          cat .github/workflows/template.md >> $outfile
          echo -e "\n -   -   -  \n" >> $outfile

          sudo make full > tmp.bdg
          echo -e "### succesfully built, signed & inserted the modules\n" >> $outfile
          cat tmp.bdg | tail -15 | sed 's/^/    /' >> $outfile

      - name: comment
        uses: harupy/comment-on-pr@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: "body.md"

      
