name: ins

on:
  workflow_dispatch:
  pull_request:
  push:
    branch: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: ins
        run: |
          sudo make install
          sudo make ins