name: ins

on:
  workflow_dispatch:
  pull_request:
    types: [ assigned, opened, synchronize, reopened ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: ins
        run: |
          outfile=".github/workflows/body.md"
          make tag-install
          echo "## auto-build & insert kernel mods $_tag" > $outfile
          _tag="$(./tag)"
          sudo make full > tmp.bdg && head -n -10 tmp.bdg
          echo '\`\`\`' >> body.md
          cat tmp.bdg >> body.md
          echo '\`\`\`' >> body.md

      - name: comment
        uses: harupy/comment-on-pr@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: "body.md"

      
