name: ker

on:
  workflow_dispatch:
  pull_request:
    types: [ opened ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2      
    - name: ker
      run: |
        outfile=".github/workflows/body.md"
        make install-tag
        _tag="$(./tag)"
        _br="$(./tag curb)"
        echo "## kernel-auto-build $_tag" > $outfile
        echo "release-tag: $_tag" >> $outfile
        echo "branch: $_br" >> $outfile
        cat .github/workflows/template.md >> .github/workflows/body.md

    - name: comment
      uses: harupy/comment-on-pr@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        filename: "body.md"

      
