name: ker

on:
  workflow_dispatch:
  pull_request:
    types: [ assigned, opened, synchronize, reopened ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2      
    - name: ker
      run: |
        outfile=".github/workflows/body.md"
        _tag="$(./tag)"
        _br="$(./tag curb)"
        echo "## kernel-auto-build $_tag" > $outfile
        echo "release-tag: $_tag" >> $outfile
        echo "branch: $_br" >> $outfile
        cat .github/workflows/template.md >> .github/workflows/body.md
        echo "-   -   -   -   -   -" >> $outfile
        echo "### fetch-latest logs" >> $outfile
        make fetch-latest >> $outfile
        echo "### build tiny-kernel" >> $outfile
        make tiny-kernel  >> $outfile 

    - name: comment
      uses: harupy/comment-on-pr@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        filename: "body.md"

      