name: ker

on:
  workflow_dispatch:
  pull_request:
    types: [ opened ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2      
    - name: pull-notif
      run: |
        make tag-install
        outfile=".github/workflows/body.md"
        echo "## $(./tag)" > $outfile
        cat .github/workflows/template.md >> .github/workflows/body.md

    - name: comment
      uses: harupy/comment-on-pr@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        filename: "body.md"

      
